name: SSH Command
inputs:
  action:
    required: true
    description: 'Command list: scp, ssh-command'
  host:
    required: true
  port:
    required: false
    default: 22
  user:
    required: true
  key:
    required: true
  script:
    required: false
  source:
    required: false
  target:
    required: false
    default: '.'
  variables:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
